@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.globl	gBlackWhitePalette
.data
	.align	2, 0
	.type	 gBlackWhitePalette,object
	.size	 gBlackWhitePalette,32
gBlackWhitePalette:
	.short	0x0
	.short	0x7fff
	.space	28
	.globl	gUnknown_02000D68
	.type	 gUnknown_02000D68,object
gUnknown_02000D68:
	.byte	0x5
	.byte	0x6
	.byte	0x6
	.byte	0x7
	.byte	0x8
	.byte	0x7
	.size	 gUnknown_02000D68,6
	.globl	gUnknown_02000D6E
	.type	 gUnknown_02000D6E,object
gUnknown_02000D6E:
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.byte	0x4
	.byte	0x0
	.size	 gUnknown_02000D6E,6
	.section .rodata
	.align	2, 0
.LC5:
	.ascii	"\203}\203\212\203I\201@\202\226\202\223\201D\201@\203h\203"
	.ascii	"\223\203L\201[\203R\203\223\203O\201@\203J\201[\203h\202"
	.ascii	"\205\201{\000"
	.align	2, 0
.LC8:
	.ascii	"\203}\203\212\203I\201@\202\226\202\223\201D\201@\203h\203"
	.ascii	"\223\203L\201[\203R\203\223\203O\000"
.text
	.align	2, 0
	.globl	AgbMain
	.type	 AgbMain,function
	.thumb_func
AgbMain:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	add	sp, sp, #-0x100
	ldr	r4, .L11
	ldr	r0, .L11+0x4
	ldr	r2, [r4]
	mov	r1, #0x64
	bl	_call_via_r2
	mov	r0, #0x84
	lsl	r0, r0, #0x2
	ldr	r3, [r4]
	mov	r1, #0x4e
	mov	r2, #0x0
	bl	_call_via_r3
	ldr	r6, .L11+0x8
	ldr	r1, .L11+0xc
	ldr	r5, [r4]
	add	r0, r6, #0
	mov	r2, #0x0
	mov	r3, #0x10
	bl	_call_via_r5
	ldr	r1, .L11+0x10
	ldr	r5, [r4]
	add	r0, r6, #0
	mov	r2, #0x10
	mov	r3, #0x10
	bl	_call_via_r5
	bl	sub_02000260
	ldr	r6, .L11+0x14
	mov	r1, #0xb5
	lsl	r1, r1, #0x2
	add	r0, r6, #0
	bl	sub_02000980
	ldr	r0, .L11+0x18
	ldr	r1, .L11+0x1c
	ldr	r2, [r4]
	bl	_call_via_r2
	mov	r0, #0xa4
	lsl	r0, r0, #0x2
	ldr	r1, .L11+0x20
	mov	r2, #0x81
	lsl	r2, r2, #0x1
	ldr	r3, .L11+0x24
	ldr	r5, [r4]
	bl	_call_via_r5
	lsl	r0, r0, #0x18
	lsr	r7, r0, #0x18
	ldr	r0, .L11+0x28
	lsl	r1, r7, #0x8
	ldr	r2, [r4]
	bl	_call_via_r2
	ldr	r0, .L11+0x2c
	ldr	r3, [r4]
	add	r1, r7, #0
	mov	r2, #0x0
	bl	_call_via_r3
	ldr	r0, .L11+0x30
	ldr	r2, [r4]
	add	r1, r7, #0
	bl	_call_via_r2
	mov	r0, #0xa6
	lsl	r0, r0, #0x2
	mov	r2, #0x80
	lsl	r2, r2, #0x1
	ldr	r3, [r4]
	add	r1, r7, #0
	bl	_call_via_r3
	ldr	r0, .L11+0x34
	mov	r2, #0xa1
	lsl	r2, r2, #0x3
	ldr	r3, .L11+0x38
	ldr	r4, [r4]
	add	r1, r7, #0
	bl	_call_via_r4
	mov	r1, sp
	mov	r0, #0x81
	strb	r0, [r1]
	mov	r0, #0x75
	strb	r0, [r1, #0x1]
	add	r2, r6, #0
	add	r2, r2, #0x10
	add	r1, r1, #0x2
	ldrb	r0, [r6, #0x10]
	cmp	r0, #0
	beq	.L4	@cond_branch
.L5:
	ldrb	r0, [r2]
	strb	r0, [r1]
	add	r2, r2, #0x1
	add	r1, r1, #0x1
	ldrb	r0, [r2]
	cmp	r0, #0
	bne	.L5	@cond_branch
.L4:
	mov	r0, #0x81
	strb	r0, [r1]
	add	r1, r1, #0x1
	mov	r0, #0x76
	strb	r0, [r1]
	mov	r0, #0x0
	strb	r0, [r1, #0x1]
	ldr	r5, .L11
	mov	r2, #0xa2
	lsl	r2, r2, #0x3
	ldr	r4, [r5]
	ldr	r0, .L11+0x34
	add	r1, r7, #0
	mov	r3, sp
	bl	_call_via_r4
	ldr	r2, .L11+0x3c
	ldr	r3, .L11+0x40
	ldr	r4, [r5]
	mov	r0, #0xa4
	lsl	r0, r0, #0x2
	ldr	r1, .L11+0x20
	bl	_call_via_r4
	lsl	r0, r0, #0x18
	lsr	r7, r0, #0x18
	lsl	r1, r7, #0x8
	ldr	r2, [r5]
	ldr	r0, .L11+0x28
	bl	_call_via_r2
	ldr	r0, .L11+0x2c
	mov	sl, r0
	ldr	r3, [r5]
	add	r1, r7, #0
	mov	r2, #0x0
	bl	_call_via_r3
	ldr	r0, .L11+0x30
	mov	r8, r0
	ldr	r2, [r5]
	add	r1, r7, #0
	bl	_call_via_r2
	mov	r6, #0xa6
	lsl	r6, r6, #0x2
	mov	r0, #0x80
	lsl	r0, r0, #0x1
	mov	r9, r0
	ldr	r3, [r5]
	add	r0, r6, #0
	add	r1, r7, #0
	mov	r2, r9
	bl	_call_via_r3
	ldr	r3, .L11+0x44
	ldr	r4, [r5]
	mov	r0, #0xa4
	lsl	r0, r0, #0x2
	ldr	r1, .L11+0x20
	mov	r2, #0x0
	bl	_call_via_r4
	add	r4, r0, #0
	lsl	r4, r4, #0x18
	lsr	r4, r4, #0x18
	lsl	r1, r4, #0x8
	mov	r0, #0x2
	orr	r1, r1, r0
	ldr	r2, [r5]
	ldr	r0, .L11+0x28
	bl	_call_via_r2
	ldr	r3, [r5]
	mov	r0, sl
	add	r1, r4, #0
	mov	r2, #0x0
	bl	_call_via_r3
	ldr	r2, [r5]
	mov	r0, r8
	add	r1, r4, #0
	bl	_call_via_r2
	ldr	r3, [r5]
	add	r0, r6, #0
	add	r1, r4, #0
	mov	r2, r9
	bl	_call_via_r3
	ldr	r2, .L11+0x48
	ldr	r3, .L11+0x4c
	ldr	r6, [r5]
	ldr	r0, .L11+0x34
	add	r1, r4, #0
	bl	_call_via_r6
	ldr	r0, .L11+0x50
	ldr	r3, [r5]
	mov	r1, #0x10
	mov	r2, #0x23
	bl	_call_via_r3
	mov	r0, #0x80
	lsl	r0, r0, #0x2
	ldr	r2, [r5]
	mov	r1, #0x10
	bl	_call_via_r2
	mov	r4, #0x0
	ldr	r0, .L11+0x54
	strb	r4, [r0]
	add	r6, r0, #0
.L9:
	ldr	r2, [r5]
	mov	r0, #0xc0
	lsl	r0, r0, #0x2
	mov	r1, #0x1
	bl	_call_via_r2
	add	r0, r4, #0
	bl	sub_020008A4
	strb	r0, [r6]
	add	r0, r7, #0
	bl	sub_020009A0
	ldr	r1, [r5]
	ldr	r0, .L11+0x58
	bl	_call_via_r1
	lsl	r0, r0, #0x10
	lsr	r4, r0, #0x10
	ldrb	r0, [r6]
	cmp	r0, #0
	beq	.L9	@cond_branch
	mov	r0, #0x2
	add	sp, sp, #0x100
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
.L12:
	.align	2, 0
.L11:
	.word	gEReaderAPIEntry
	.word	0x2ea
	.word	0x27e
	.word	gUnknown_02001070
	.word	gBlackWhitePalette
	.word	gLevelData
	.word	0x2c3
	.word	sub_020005C4
	.word	0x101
	.word	0x1e03
	.word	0x29a
	.word	0x291
	.word	0x292
	.word	0x299
	.word	.LC5
	.word	0x105
	.word	0x1e10
	.word	0x1e02
	.word	0x402
	.word	.LC8
	.word	0x21a
	.word	gUnknown_020010B4
	.word	0x301
.Lfe1:
	.size	 AgbMain,.Lfe1-AgbMain
	.globl	unusedString
	.section .rodata
	.align	2, 0
	.type	 unusedString,object
	.size	 unusedString,15
unusedString:
	.ascii	"MultiSio010918\000"
	.globl	gStringTable
.data
	.align	2, 0
	.type	 gStringTable,object
gStringTable:
	.word	.LC11
	.word	.LC11
	.word	.LC12
	.word	.LC13
	.word	.LC14
	.word	.LC13
	.section .rodata
	.align	2, 0
.LC14:
	.ascii	"\202\273\202\244\202\265\202\361\202\251\202\361\202\350"
	.ascii	"\202\345\202\244\201B\n\n\202`\203{\203^\203\223\202\360"
	.ascii	"\202\250\202\267\202\306\202\340\202\244\202\242\202\277"
	.ascii	"\202\307\202\273\202\244\202\265\202\361\202\265\202\334"
	.ascii	"\202\267\201B\n\202a\203{\203^\203\223\202\360\202\250\202"
	.ascii	"\267\202\306\203L\203\203\203\223\203Z\203\213\202\265\202"
	.ascii	"\334\202\267\201B\000"
	.align	2, 0
.LC13:
	.ascii	"\202\273\202\244\202\265\202\361\202\277\202\343\202\244"
	.ascii	"\201B\n\n\203Q\201[\203\200\203{\201[\203C\203A\203h\203"
	.ascii	"o\203\223\203X\202\314\202\305\202\361\202\260\202\361\202"
	.ascii	"\360\202\253\202\301\202\275\202\350\201A\202\302\202\244"
	.ascii	"\202\265\202\361\n\203P\201[\203u\203\213\202\360\202\312"
	.ascii	"\202\242\202\275\202\350\202\265\202\310\202\242\202\305"
	.ascii	"\202\255\202\276\202\263\202\242\201B\000"
	.align	2, 0
.LC12:
	.ascii	"\202\273\202\244\202\265\202\361\202\314\202\346\202\244"
	.ascii	"\202\242\202\252\202\305\202\253\202\334\202\265\202\275"
	.ascii	"\201B\n\n\202\302\202\244\202\265\202\361\202\275\202\242"
	.ascii	"\202\253\202\277\202\343\202\244\201B\000"
	.align	2, 0
.LC11:
	.ascii	"\202\273\202\244\202\265\202\361\202\314\202\346\202\244"
	.ascii	"\202\242\202\252\202\305\202\253\202\334\202\265\202\275"
	.ascii	"\201B\n\n\203J\201[\203h\202\205\203\212\201[\203_\201[\201"
	.ascii	"{\202\252\202\263\202\263\202\301\202\304\202\242\202\351"
	.ascii	"\203Q\201[\203\200\203{\201[\203C\203A\203h\203o\203\223"
	.ascii	"\n\203X\202\306\201A\203}\203\212\203I\202\226\202\223\201"
	.ascii	"D\203h\203\223\203L\201[\203R\203\223\203O\202\314\203J\201"
	.ascii	"[\203g\203\212\203b\203W\202\252\202\263\202\263\n\202\301"
	.ascii	"\202\304\202\242\202\351\203Q\201[\203\200\203{\201[\203"
	.ascii	"C\203A\203h\203o\203\223\203X\202\360\201A\202\302\202\244"
	.ascii	"\202\265\202\361\203P\201[\203u\203\213\202\305\n\202\302"
	.ascii	"\202\310\202\254\201A\203\201\203j\203\205\201[\202\305\201"
	.ascii	"u\203X\203e\201[\203W\202\360\202\302\202\242\202\251\201"
	.ascii	"v\202\360\202\246\202\347\202\361\202\305\203X\203^\n\201"
	.ascii	"[\203g\202\263\202\271\202\304\202\255\202\276\202\263\202"
	.ascii	"\242\201B\n\202a\203{\203^\203\223\202\360\202\250\202\267"
	.ascii	"\202\306\203L\203\203\203\223\203Z\203\213\202\265\202\334"
	.ascii	"\202\267\201B\n\000"
	.size	 gStringTable,24
.text
	.align	2, 0
	.globl	sub_02000260
	.type	 sub_02000260,function
	.thumb_func
sub_02000260:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	add	sp, sp, #-0x4
	ldr	r3, .L19
	mov	r4, #0x0
	strh	r4, [r3]
	ldr	r2, .L19+0x4
	ldrh	r1, [r2]
	ldr	r0, .L19+0x8
	and	r0, r0, r1
	strh	r0, [r2]
	mov	r0, #0x1
	strh	r0, [r3]
	ldr	r0, .L19+0xc
	strh	r4, [r0]
	sub	r2, r2, #0xd8
	mov	r0, #0x80
	lsl	r0, r0, #0x6
	str	r0, [r2]
	ldrh	r0, [r2]
	ldr	r3, .L19+0x10
	add	r1, r3, #0
	orr	r0, r0, r1
	strh	r0, [r2]
	mov	r0, #0x0
	str	r0, [sp]
	ldr	r4, .L19+0x14
	ldr	r2, .L19+0x18
	mov	r0, sp
	add	r1, r4, #0
	bl	CpuSet
	mov	r0, #0x1
	neg	r0, r0
	str	r0, [r4, #0x14]
	add	r0, r4, #0
	add	r0, r0, #0x60
	str	r0, [r4, #0x28]
	add	r0, r0, #0x18
	str	r0, [r4, #0x2c]
	mov	r3, #0x0
	add	r5, r4, #0
	add	r5, r5, #0xc0
	mov	r2, #0x0
	mov	r7, #0x30
	add	r7, r7, r4
	mov	r8, r7
	mov	r0, #0x90
	add	r0, r0, r4
	mov	ip, r0
	add	r6, r4, #0
	add	r6, r6, #0xa8
	mov	r7, #0x40
	add	r7, r7, r4
	mov	r9, r7
.L17:
	lsl	r1, r3, #0x2
	mov	r7, ip
	add	r0, r2, r7
	mov	r7, r8
	add	r7, r7, #0x4
	mov	r8, r7
	sub	r7, r7, #0x4
	stmia	r7!, {r0}
	add	r0, r2, r6
	mov	r7, r9
	add	r7, r7, #0x4
	mov	r9, r7
	sub	r7, r7, #0x4
	stmia	r7!, {r0}
	add	r0, r4, #0
	add	r0, r0, #0x50
	add	r1, r1, r0
	str	r5, [r1]
	add	r5, r5, #0x48
	add	r2, r2, #0x48
	add	r3, r3, #0x1
	cmp	r3, #0x1
	ble	.L17	@cond_branch
	mov	r0, #0x0
	ldr	r3, .L19
	strh	r0, [r3]
	ldr	r2, .L19+0x4
	ldrh	r0, [r2]
	mov	r1, #0x80
	orr	r0, r0, r1
	strh	r0, [r2]
	mov	r0, #0x1
	strh	r0, [r3]
	add	sp, sp, #0x4
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L20:
	.align	2, 0
.L19:
	.word	0x4000208
	.word	0x4000200
	.word	0xff3f
	.word	0x4000134
	.word	0x4003
	.word	gUnknown_020010D0
	.word	0x5000048
.Lfe2:
	.size	 sub_02000260,.Lfe2-sub_02000260
	.align	2, 0
	.globl	sub_02000340
	.type	 sub_02000340,function
	.thumb_func
sub_02000340:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	mov	r8, r0
	mov	ip, r1
	ldr	r6, .L44
	ldr	r5, [r6]
	ldr	r0, .L44+0x4
	ldrb	r2, [r0, #0x1]
	add	r7, r0, #0
	cmp	r2, #0x1
	beq	.L30	@cond_branch
	cmp	r2, #0x1
	bgt	.L37	@cond_branch
	cmp	r2, #0
	beq	.L26	@cond_branch
	b	.L25
.L45:
	.align	2, 0
.L44:
	.word	0x4000128
	.word	gUnknown_020010D0
.L37:
	cmp	r2, #0x2
	beq	.L34	@cond_branch
	b	.L25
.L26:
	mov	r1, #0x30
	add	r0, r5, #0
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L27	@cond_branch
	mov	r0, #0x88
	add	r4, r5, #0
	and	r4, r4, r0
	cmp	r4, #0x8
	bne	.L25	@cond_branch
	mov	r1, #0x4
	add	r0, r5, #0
	and	r0, r0, r1
	lsl	r0, r0, #0x18
	lsr	r2, r0, #0x18
	cmp	r2, #0
	bne	.L27	@cond_branch
	ldr	r1, [r7, #0x14]
	mov	r0, #0x1
	neg	r0, r0
	cmp	r1, r0
	bne	.L27	@cond_branch
	ldr	r3, .L46
	strh	r2, [r3]
	ldr	r2, .L46+0x4
	ldrh	r1, [r2]
	ldr	r0, .L46+0x8
	and	r0, r0, r1
	strh	r0, [r2]
	ldrh	r0, [r2]
	mov	r1, #0x40
	orr	r0, r0, r1
	strh	r0, [r2]
	mov	r0, #0x1
	strh	r0, [r3]
	ldrb	r1, [r6, #0x1]
	mov	r0, #0x41
	neg	r0, r0
	and	r0, r0, r1
	strb	r0, [r6, #0x1]
	ldr	r1, .L46+0xc
	mov	r0, #0xc0
	strh	r0, [r1]
	sub	r1, r1, #0xf6
	ldr	r0, .L46+0x10
	str	r0, [r1]
	strb	r4, [r7]
.L27:
	mov	r0, #0x1
	strb	r0, [r7, #0x1]
.L30:
	ldr	r1, .L46+0x14
	ldrb	r0, [r1, #0x2]
	cmp	r0, #0
	beq	.L34	@cond_branch
	ldrb	r0, [r1, #0xa]
	cmp	r0, #0x7
	bhi	.L32	@cond_branch
	add	r0, r0, #0x1
	strb	r0, [r1, #0xa]
	b	.L34
.L47:
	.align	2, 0
.L46:
	.word	0x4000208
	.word	0x4000200
	.word	0xff7f
	.word	0x4000202
	.word	0xb1fc
	.word	gUnknown_020010D0
.L32:
	mov	r0, #0x2
	strb	r0, [r1, #0x1]
.L34:
	mov	r0, ip
	bl	sub_020004E0
	mov	r0, r8
	bl	sub_0200046C
.L25:
	ldr	r1, .L48
	ldrb	r0, [r1, #0xb]
	add	r0, r0, #0x1
	strb	r0, [r1, #0xb]
	ldrb	r3, [r1, #0x3]
	ldrb	r0, [r1, #0x2]
	lsl	r2, r0, #0x8
	ldrb	r0, [r1]
	add	r7, r1, #0
	cmp	r0, #0x8
	bne	.L38	@cond_branch
	mov	r0, #0x80
	orr	r0, r0, r2
	orr	r0, r0, r3
	b	.L39
.L49:
	.align	2, 0
.L48:
	.word	gUnknown_020010D0
.L38:
	add	r0, r3, #0
	orr	r0, r0, r2
.L39:
	add	r2, r0, #0
	ldrb	r0, [r7, #0x9]
	cmp	r0, #0
	beq	.L41	@cond_branch
	mov	r0, #0x80
	lsl	r0, r0, #0x5
	orr	r2, r2, r0
.L41:
	ldrb	r0, [r7, #0xa]
	lsr	r0, r0, #0x3
	lsl	r1, r0, #0xf
	lsl	r0, r5, #0x1a
	lsr	r0, r0, #0x1e
	cmp	r0, #0x1
	bls	.L42	@cond_branch
	mov	r0, #0x80
	lsl	r0, r0, #0x6
	orr	r0, r0, r1
	orr	r0, r0, r2
	b	.L43
.L42:
	add	r0, r2, #0
	orr	r0, r0, r1
.L43:
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe3:
	.size	 sub_02000340,.Lfe3-sub_02000340
	.align	2, 0
	.globl	sub_0200046C
	.type	 sub_0200046C,function
	.thumb_func
sub_0200046C:
	push	{r4, r5, lr}
	mov	r5, #0x0
	ldr	r4, .L58
	ldr	r2, [r4, #0x28]
	ldrb	r1, [r4, #0xb]
	strb	r1, [r2]
	ldr	r3, [r4, #0x28]
	ldrb	r1, [r4, #0x2]
	ldrb	r2, [r4, #0x3]
	eor	r1, r1, r2
	strb	r1, [r3, #0x1]
	ldr	r1, [r4, #0x28]
	strh	r5, [r1, #0x2]
	ldr	r1, [r4, #0x28]
	add	r1, r1, #0x4
	ldr	r2, .L58+0x4
	bl	CpuSet
	mov	r2, #0x0
	ldr	r1, [r4, #0x28]
.L54:
	ldrh	r0, [r1]
	add	r5, r5, r0
	add	r1, r1, #0x2
	add	r2, r2, #0x1
	cmp	r2, #0x9
	bls	.L54	@cond_branch
	add	r2, r4, #0
	ldr	r1, [r2, #0x28]
	mvn	r0, r5
	sub	r0, r0, #0xc
	strh	r0, [r1, #0x2]
	ldrb	r0, [r2]
	cmp	r0, #0
	beq	.L56	@cond_branch
	ldr	r1, .L58+0x8
	mov	r0, #0x0
	strh	r0, [r1]
.L56:
	mov	r0, #0x1
	neg	r0, r0
	str	r0, [r4, #0x14]
	ldrb	r0, [r4]
	cmp	r0, #0
	beq	.L57	@cond_branch
	ldrb	r0, [r4, #0x8]
	cmp	r0, #0
	beq	.L57	@cond_branch
	ldr	r1, .L58+0x8
	mov	r0, #0xc0
	strh	r0, [r1]
.L57:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
.L59:
	.align	2, 0
.L58:
	.word	gUnknown_020010D0
	.word	0x4000004
	.word	0x400010e
.Lfe4:
	.size	 sub_0200046C,.Lfe4-sub_0200046C
	.align	2, 0
	.globl	sub_020004E0
	.type	 sub_020004E0,function
	.thumb_func
sub_020004E0:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	add	sp, sp, #-0x10
	str	r0, [sp, #0xc]
	mov	r1, #0x0
	str	r1, [sp]
	ldr	r0, .L77
	strh	r1, [r0]
	ldr	r3, .L77+0x4
	add	r0, sp, #0x4
	mov	sl, r0
	add	r1, sp, #0x8
	mov	r9, r1
	add	r2, r3, #0
	add	r2, r2, #0x3c
	mov	r4, #0x3
.L64:
	ldr	r1, [r2, #0x10]
	ldr	r0, [r2]
	str	r0, [r2, #0x10]
	stmia	r2!, {r1}
	sub	r4, r4, #0x1
	cmp	r4, #0
	bge	.L64	@cond_branch
	ldr	r0, [r3]
	str	r0, [sp, #0x4]
	mov	r2, #0x0
	str	r2, [r3]
	ldr	r1, .L77
	mov	r0, #0x1
	strh	r0, [r1]
	sub	r0, r3, #0x4
	strb	r2, [r0, #0x3]
	mov	r4, #0x0
	mov	r8, r0
	mov	r7, r8
	add	r7, r7, #0x50
.L69:
	mov	r3, #0x0
	mov	r2, #0x0
	lsl	r5, r4, #0x2
	add	r6, r4, #0x1
	add	r0, r5, r7
	ldr	r1, [r0]
.L73:
	ldrh	r0, [r1]
	add	r3, r3, r0
	add	r1, r1, #0x2
	add	r2, r2, #0x1
	cmp	r2, #0x9
	bls	.L73	@cond_branch
	mov	r2, sl
	add	r0, r2, r4
	ldrb	r0, [r0]
	cmp	r0, #0
	beq	.L75	@cond_branch
	lsl	r0, r3, #0x10
	asr	r0, r0, #0x10
	mov	r1, #0xd
	neg	r1, r1
	cmp	r0, r1
	bne	.L75	@cond_branch
	add	r0, r5, r7
	ldr	r0, [r0]
	add	r0, r0, #0x4
	lsl	r1, r4, #0x4
	ldr	r2, [sp, #0xc]
	add	r1, r2, r1
	ldr	r2, .L77+0x8
	bl	CpuSet
	mov	r0, #0x1
	lsl	r0, r0, r4
	mov	r2, r8
	ldrb	r1, [r2, #0x3]
	orr	r0, r0, r1
	strb	r0, [r2, #0x3]
.L75:
	mov	r0, #0x0
	str	r0, [sp, #0x8]
	add	r0, r5, r7
	ldr	r1, [r0]
	add	r1, r1, #0x4
	mov	r0, r9
	ldr	r2, .L77+0xc
	bl	CpuSet
	add	r4, r6, #0
	cmp	r4, #0x1
	ble	.L69	@cond_branch
	ldr	r1, .L77+0x10
	ldrb	r0, [r1, #0x2]
	ldrb	r2, [r1, #0x3]
	orr	r0, r0, r2
	strb	r0, [r1, #0x2]
	ldrb	r0, [r1, #0x3]
	add	sp, sp, #0x10
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
.L78:
	.align	2, 0
.L77:
	.word	0x4000208
	.word	gUnknown_020010D0+0x4
	.word	0x4000004
	.word	0x5000004
	.word	gUnknown_020010D0
.Lfe5:
	.size	 sub_020004E0,.Lfe5-sub_020004E0
	.align	2, 0
	.globl	sub_020005C4
	.type	 sub_020005C4,function
	.thumb_func
sub_020005C4:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	add	sp, sp, #-0x8
	ldr	r0, .L94
	ldr	r1, [r0, #0x4]		@ created by thumb_load_double_from_address
	ldr	r0, [r0]		@ created by thumb_load_double_from_address
	str	r0, [sp]
	str	r1, [sp, #0x4]
	ldr	r2, .L94+0x4
	ldr	r3, .L94+0x8
	ldr	r0, [r3]
	lsl	r0, r0, #0x19
	lsr	r0, r0, #0x1f
	strb	r0, [r2, #0x9]
	ldr	r1, [r2, #0x14]
	mov	r0, #0x1
	neg	r0, r0
	mov	ip, r2
	cmp	r1, r0
	bne	.L80	@cond_branch
	ldr	r0, .L94+0xc
	strh	r0, [r3, #0x2]
	ldr	r1, [r2, #0x2c]
	ldr	r0, [r2, #0x28]
	str	r0, [r2, #0x2c]
	str	r1, [r2, #0x28]
	b	.L81
.L95:
	.align	2, 0
.L94:
	.word	0x4000120
	.word	gUnknown_020010D0
	.word	0x4000128
	.word	0xfefe
.L80:
	cmp	r1, #0
	blt	.L81	@cond_branch
	mov	r2, ip
	ldr	r0, [r2, #0x2c]
	lsl	r1, r1, #0x1
	add	r1, r1, r0
	ldrh	r0, [r1]
	strh	r0, [r3, #0x2]
.L81:
	mov	r1, ip
	ldr	r0, [r1, #0x14]
	cmp	r0, #0xa
	bgt	.L83	@cond_branch
	add	r0, r0, #0x1
	str	r0, [r1, #0x14]
.L83:
	mov	r2, #0x0
	mov	r8, r2
	mov	sl, ip
	mov	r9, r2
	mov	r6, ip
	add	r6, r6, #0x18
	mov	r5, sp
.L87:
	ldrh	r0, [r5]
	mov	r1, r8
	lsl	r7, r1, #0x2
	ldr	r2, .L96
	cmp	r0, r2
	bne	.L88	@cond_branch
	ldr	r0, [r6]
	cmp	r0, #0x9
	ble	.L88	@cond_branch
	mov	r0, #0x1
	neg	r0, r0
	str	r0, [r6]
	b	.L89
.L97:
	.align	2, 0
.L96:
	.word	0xfefe
.L88:
	mov	r0, sl
	add	r0, r0, #0x30
	mov	r1, r9
	add	r4, r1, r0
	ldr	r2, [r6]
	ldr	r3, [r4]
	lsl	r0, r2, #0x1
	add	r0, r0, r3
	ldrh	r1, [r5]
	strh	r1, [r0]
	cmp	r2, #0x9
	bne	.L89	@cond_branch
	mov	r0, ip
	add	r0, r0, #0x40
	add	r0, r7, r0
	ldr	r1, [r0]
	str	r3, [r0]
	str	r1, [r4]
	mov	r0, ip
	add	r0, r0, #0x4
	add	r0, r0, r8
	mov	r1, #0x1
	strb	r1, [r0]
.L89:
	ldr	r0, [r6]
	cmp	r0, #0xa
	bgt	.L86	@cond_branch
	add	r0, r0, #0x1
	str	r0, [r6]
.L86:
	mov	r2, #0x4
	add	r9, r9, r2
	add	r6, r6, #0x4
	add	r5, r5, #0x2
	mov	r0, #0x1
	add	r8, r8, r0
	mov	r1, r8
	cmp	r1, #0x1
	ble	.L87	@cond_branch
	mov	r2, ip
	ldrb	r0, [r2]
	cmp	r0, #0x8
	bne	.L93	@cond_branch
	ldr	r3, .L98
	mov	r0, #0x0
	strh	r0, [r3]
	ldr	r2, .L98+0x4
	ldrh	r0, [r2]
	mov	r1, #0x80
	orr	r0, r0, r1
	strh	r0, [r2]
	mov	r0, #0xc0
	strh	r0, [r3]
.L93:
	add	sp, sp, #0x8
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L99:
	.align	2, 0
.L98:
	.word	0x400010e
	.word	0x4000128
.Lfe6:
	.size	 sub_020005C4,.Lfe6-sub_020005C4
	.align	2, 0
	.globl	sub_020006D8
	.type	 sub_020006D8,function
	.thumb_func
sub_020006D8:
	push	{lr}
	ldr	r1, .L102
	ldrb	r0, [r1]
	cmp	r0, #0
	beq	.L101	@cond_branch
	mov	r0, #0x1
	strb	r0, [r1, #0x8]
.L101:
	pop	{r0}
	bx	r0
.L103:
	.align	2, 0
.L102:
	.word	gUnknown_020010D0
.Lfe7:
	.size	 sub_020006D8,.Lfe7-sub_020006D8
	.align	2, 0
	.globl	sub_020006F0
	.type	 sub_020006F0,function
	.thumb_func
sub_020006F0:
	push	{r4, lr}
	ldr	r3, .L105
	mov	r4, #0x0
	strh	r4, [r3]
	ldr	r2, .L105+0x4
	ldrh	r1, [r2]
	ldr	r0, .L105+0x8
	and	r0, r0, r1
	strh	r0, [r2]
	mov	r0, #0x1
	strh	r0, [r3]
	ldr	r1, .L105+0xc
	ldr	r2, .L105+0x10
	add	r0, r2, #0
	strh	r0, [r1]
	sub	r1, r1, #0x1c
	ldr	r0, .L105+0x14
	str	r0, [r1]
	add	r1, r1, #0xf6
	mov	r0, #0xc0
	strh	r0, [r1]
	ldr	r0, .L105+0x18
	strb	r4, [r0, #0x8]
	pop	{r4}
	pop	{r0}
	bx	r0
.L106:
	.align	2, 0
.L105:
	.word	0x4000208
	.word	0x4000200
	.word	0xff3f
	.word	0x4000128
	.word	0x2003
	.word	0xb1fc
	.word	gUnknown_020010D0
.Lfe8:
	.size	 sub_020006F0,.Lfe8-sub_020006F0
	.align	2, 0
	.globl	sub_02000740
	.type	 sub_02000740,function
	.thumb_func
sub_02000740:
	ldr	r1, .L108
	mov	r0, #0x0
	strb	r0, [r1, #0x1]
	bx	lr
.L109:
	.align	2, 0
.L108:
	.word	gUnknown_020010D0
.Lfe9:
	.size	 sub_02000740,.Lfe9-sub_02000740
	.align	2, 0
	.globl	sub_0200074C
	.type	 sub_0200074C,function
	.thumb_func
sub_0200074C:
	push	{r4, r5, r6, lr}
	ldr	r2, .L116
	ldr	r0, .L116+0x4
	ldr	r1, [r2, #0x34]
	add	r0, r1, r0
	ldrb	r0, [r0]
	strb	r0, [r2, #0x4]
	cmp	r1, #0x3
	bne	.L111	@cond_branch
	mov	r5, #0xc
	ldrb	r6, [r2, #0x15]
	mov	r4, r6
	mul	r4, r4, r5
	ldr	r1, [r2, #0x3c]
	cmp	r4, r1
	blt	.L112	@cond_branch
	ldr	r6, [r2, #0x40]
	mov	r5, #0x0
	mov	r0, #0x4
	strb	r0, [r2, #0x4]
	str	r0, [r2, #0x34]
	ldr	r1, .L116+0x8
	ldr	r0, .L116+0xc
	ldr	r2, [r1]
	mov	r1, #0x3
	bl	_call_via_r2
	b	.L113
.L117:
	.align	2, 0
.L116:
	.word	gUnknown_020011F0
	.word	gUnknown_02000D68
	.word	gEReaderAPIEntry
	.word	0x105
.L112:
	add	r0, r4, #0
	add	r0, r0, #0xc
	cmp	r0, r1
	blt	.L113	@cond_branch
	sub	r5, r1, r4
	mov	r0, #0x4
	strb	r0, [r2, #0x4]
	str	r0, [r2, #0x34]
	ldr	r1, .L118
	ldr	r0, .L118+0x4
	ldr	r2, [r1]
	mov	r1, #0x3
	bl	_call_via_r2
.L113:
	cmp	r5, #0
	ble	.L115	@cond_branch
	ldr	r1, .L118+0x8
	ldr	r0, [r1, #0x38]
	add	r0, r0, r4
	add	r1, r1, #0x8
	lsr	r2, r5, #0x1f
	add	r2, r5, r2
	lsl	r2, r2, #0xa
	lsr	r2, r2, #0xb
	bl	CpuSet
.L115:
	ldr	r0, .L118+0x8
	strb	r6, [r0, #0x5]
	strb	r5, [r0, #0x6]
.L111:
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L119:
	.align	2, 0
.L118:
	.word	gEReaderAPIEntry
	.word	0x105
	.word	gUnknown_020011F0
.Lfe10:
	.size	 sub_0200074C,.Lfe10-sub_0200074C
	.align	2, 0
	.globl	sub_020007E0
	.type	 sub_020007E0,function
	.thumb_func
sub_020007E0:
	push	{lr}
	ldr	r0, .L145
	ldrb	r2, [r0, #0x14]
	ldr	r1, [r0, #0x34]
	add	r3, r0, #0
	cmp	r1, #0x5
	bhi	.L123	@cond_branch
	lsl	r0, r1, #0x2
	ldr	r1, .L145+0x4
	add	r0, r0, r1
	ldr	r0, [r0]
	mov	pc, r0
.L146:
	.align	2, 0
.L145:
	.word	gUnknown_020011F0
	.word	.L142
	.align	2, 0
	.align	2, 0
.L142:
	.word	.L123
	.word	.L127
	.word	.L129
	.word	.L133
	.word	.L121
	.word	.L138
.L123:
	cmp	r2, #0x1
	beq	.L143	@cond_branch
	cmp	r2, #0x2
	bne	.L121	@cond_branch
	b	.L143
.L127:
	cmp	r2, #0x2
	bne	.L121	@cond_branch
	str	r2, [r3, #0x34]
	ldr	r1, .L147
	ldr	r0, .L147+0x4
	ldr	r2, [r1]
	mov	r1, #0xb
	bl	_call_via_r2
	b	.L121
.L148:
	.align	2, 0
.L147:
	.word	gEReaderAPIEntry
	.word	0x105
.L129:
	ldr	r0, [r3, #0x48]
	add	r0, r0, #0x1
	str	r0, [r3, #0x48]
	cmp	r2, #0x3
	bne	.L130	@cond_branch
	str	r2, [r3, #0x34]
	ldr	r1, .L149
	ldr	r0, .L149+0x4
	ldr	r2, [r1]
	mov	r1, #0x2
	bl	_call_via_r2
	b	.L121
.L150:
	.align	2, 0
.L149:
	.word	gEReaderAPIEntry
	.word	0x105
.L130:
	cmp	r2, #0x1
	bne	.L121	@cond_branch
	b	.L143
.L133:
	mov	r0, #0x1
	str	r0, [r3, #0x4c]
	cmp	r2, #0x4
	beq	.L144	@cond_branch
	cmp	r2, #0x3
	beq	.L121	@cond_branch
	mov	r0, #0x5
	str	r0, [r3, #0x34]
	b	.L121
.L138:
	cmp	r2, #0x4
	bne	.L139	@cond_branch
.L144:
	str	r2, [r3, #0x34]
	ldr	r1, .L151
	ldr	r0, .L151+0x4
	ldr	r2, [r1]
	mov	r1, #0x3
	bl	_call_via_r2
	b	.L121
.L152:
	.align	2, 0
.L151:
	.word	gEReaderAPIEntry
	.word	0x105
.L139:
	cmp	r2, #0x3
	bne	.L121	@cond_branch
.L143:
	str	r2, [r3, #0x34]
.L121:
	mov	r0, #0x0
	pop	{r1}
	bx	r1
.Lfe11:
	.size	 sub_020007E0,.Lfe11-sub_020007E0
	.align	2, 0
	.globl	sub_020008A4
	.type	 sub_020008A4,function
	.thumb_func
sub_020008A4:
	push	{r4, r5, r6, lr}
	lsl	r0, r0, #0x10
	lsr	r6, r0, #0x10
	mov	r0, #0x2
	and	r0, r0, r6
	cmp	r0, #0
	beq	.L154	@cond_branch
	ldr	r0, .L164
	ldr	r0, [r0, #0x34]
	cmp	r0, #0x1
	bls	.L155	@cond_branch
	cmp	r0, #0x4
	bne	.L154	@cond_branch
.L155:
	ldr	r1, .L164+0x4
	ldr	r0, .L164+0x8
	ldr	r2, [r1]
	mov	r1, #0x6
	bl	_call_via_r2
	mov	r0, #0x1
	b	.L162
.L165:
	.align	2, 0
.L164:
	.word	gUnknown_020011F0
	.word	gEReaderAPIEntry
	.word	0x105
.L154:
	mov	r0, #0x1
	and	r0, r0, r6
	cmp	r0, #0
	beq	.L156	@cond_branch
	ldr	r1, .L166
	ldr	r0, [r1, #0x34]
	cmp	r0, #0x4
	bne	.L156	@cond_branch
	mov	r0, #0x0
	str	r0, [r1, #0x34]
	ldr	r1, .L166+0x4
	ldr	r0, .L166+0x8
	ldr	r2, [r1]
	mov	r1, #0x5
	bl	_call_via_r2
.L156:
	add	r0, r6, #0
	bl	sub_0200074C
	ldr	r4, .L166+0xc
	add	r1, r4, #0
	add	r1, r1, #0x10
	add	r0, r4, #0
	bl	sub_02000340
	sub	r4, r4, #0x4
	str	r0, [r4]
	mov	r5, #0xc0
	lsl	r5, r5, #0x6
	and	r5, r5, r0
	cmp	r5, #0
	beq	.L157	@cond_branch
	mov	r0, #0x3c
	str	r0, [r4, #0x44]
	ldr	r1, .L166+0x10
	ldr	r0, [r4, #0x34]
	add	r0, r0, r1
	ldrb	r0, [r0]
	b	.L163
.L167:
	.align	2, 0
.L166:
	.word	gUnknown_020011F0
	.word	gEReaderAPIEntry
	.word	0x105
	.word	gUnknown_020011F0+0x4
	.word	gUnknown_02000D6E
.L157:
	cmp	r0, #0
	beq	.L158	@cond_branch
	mov	r2, #0xf
	add	r1, r0, #0
	and	r1, r1, r2
	lsr	r0, r0, #0x8
	and	r0, r0, r2
	cmp	r1, r0
	bne	.L159	@cond_branch
	add	r0, r6, #0
	bl	sub_020007E0
	str	r5, [r4, #0x44]
	b	.L158
.L159:
	ldr	r0, [r4, #0x44]
	cmp	r0, #0x3b
	bgt	.L160	@cond_branch
	add	r0, r0, #0x1
	str	r0, [r4, #0x44]
	b	.L158
.L160:
	ldr	r0, .L168
	ldr	r1, [r4, #0x34]
	add	r1, r1, r0
	ldrb	r0, [r1]
.L163:
	str	r0, [r4, #0x34]
.L158:
	mov	r0, #0x0
.L162:
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
.L169:
	.align	2, 0
.L168:
	.word	gUnknown_02000D6E
.Lfe12:
	.size	 sub_020008A4,.Lfe12-sub_020008A4
	.align	2, 0
	.globl	sub_02000980
	.type	 sub_02000980,function
	.thumb_func
sub_02000980:
	push	{r4, lr}
	ldr	r4, .L171
	mov	r2, #0x0
	str	r2, [r4, #0x34]
	str	r0, [r4, #0x38]
	str	r1, [r4, #0x3c]
	add	r0, r1, #0
	mov	r1, #0xc
	bl	__udivsi3
	str	r0, [r4, #0x40]
	pop	{r4}
	pop	{r0}
	bx	r0
.L172:
	.align	2, 0
.L171:
	.word	gUnknown_020011F0
.Lfe13:
	.size	 sub_02000980,.Lfe13-sub_02000980
	.align	2, 0
	.globl	sub_020009A0
	.type	 sub_020009A0,function
	.thumb_func
sub_020009A0:
	push	{r4, r5, r6, lr}
	lsl	r0, r0, #0x18
	lsr	r6, r0, #0x18
	ldr	r1, .L175
	ldr	r0, .L175+0x4
	ldr	r0, [r0, #0x34]
	lsl	r0, r0, #0x2
	add	r0, r0, r1
	ldr	r5, [r0]
	ldr	r1, .L175+0x8
	ldr	r0, [r1]
	cmp	r0, r5
	beq	.L174	@cond_branch
	str	r5, [r1]
	ldr	r4, .L175+0xc
	ldr	r0, .L175+0x10
	ldr	r2, [r4]
	add	r1, r6, #0
	bl	_call_via_r2
	ldr	r0, .L175+0x14
	mov	r2, #0xa0
	lsl	r2, r2, #0x3
	ldr	r4, [r4]
	add	r1, r6, #0
	add	r3, r5, #0
	bl	_call_via_r4
.L174:
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L176:
	.align	2, 0
.L175:
	.word	gStringTable
	.word	gUnknown_020011F0
	.word	gUnknown_02001060
	.word	gEReaderAPIEntry
	.word	0x292
	.word	0x299
.Lfe14:
	.size	 sub_020009A0,.Lfe14-sub_020009A0
	.align	2, 0
	.globl	CpuSet
	.type	 CpuSet,function
	.thumb_func
CpuSet:
	svc #11
	.code	16
	bx	lr
.Lfe15:
	.size	 CpuSet,.Lfe15-CpuSet

	.lcomm	gUnknown_02001060,4

	.lcomm	unusedFiller,8

	.lcomm	gUnknown_02001070,68

	.lcomm	gUnknown_020010B4,1

	.lcomm	unusedFiller2,24

	.lcomm	gUnknown_020010D0,288

	.lcomm	gUnknown_020011F0,80
