@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	AgbMain
	.type	 AgbMain,function
	.thumb_func
AgbMain:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	add	sp, sp, #-0x100
	ldr	r4, .L12
	ldr	r0, .L12+0x4
	ldr	r2, [r4]
	mov	r1, #0x64
	bl	_call_via_r2
	mov	r0, #0x84
	lsl	r0, r0, #0x2
	ldr	r3, [r4]
	mov	r1, #0x4e
	mov	r2, #0x0
	bl	_call_via_r3
	ldr	r6, .L12+0x8
	ldr	r1, .L12+0xc
	ldr	r5, [r4]
	add	r0, r6, #0
	mov	r2, #0x0
	mov	r3, #0x10
	bl	_call_via_r5
	ldr	r1, .L12+0x10
	ldr	r5, [r4]
	add	r0, r6, #0
	mov	r2, #0x10
	mov	r3, #0x10
	bl	_call_via_r5
	bl	sub_02000260
	ldr	r6, .L12+0x14
	mov	r1, #0xb5
	lsl	r1, r1, #0x2
	add	r0, r6, #0
	bl	sub_02000980
	ldr	r0, .L12+0x18
	ldr	r1, .L12+0x1c
	ldr	r2, [r4]
	bl	_call_via_r2
	mov	r0, #0xa4
	lsl	r0, r0, #0x2
	ldr	r1, .L12+0x20
	mov	r2, #0x81
	lsl	r2, r2, #0x1
	ldr	r3, .L12+0x24
	ldr	r5, [r4]
	bl	_call_via_r5
	lsl	r0, r0, #0x18
	lsr	r7, r0, #0x18
	ldr	r0, .L12+0x28
	lsl	r1, r7, #0x8
	ldr	r2, [r4]
	bl	_call_via_r2
	ldr	r0, .L12+0x2c
	ldr	r3, [r4]
	add	r1, r7, #0
	mov	r2, #0x0
	bl	_call_via_r3
	ldr	r0, .L12+0x30
	ldr	r2, [r4]
	add	r1, r7, #0
	bl	_call_via_r2
	mov	r0, #0xa6
	lsl	r0, r0, #0x2
	mov	r2, #0x80
	lsl	r2, r2, #0x1
	ldr	r3, [r4]
	add	r1, r7, #0
	bl	_call_via_r3
	ldr	r0, .L12+0x34
	mov	r2, #0xa1
	lsl	r2, r2, #0x3
	ldr	r3, .L12+0x38
	ldr	r4, [r4]
	add	r1, r7, #0
	bl	_call_via_r4
	mov	r1, sp
	mov	r0, #0x81
	strb	r0, [r1]
	mov	r0, #0x75
	strb	r0, [r1, #0x1]
	add	r2, r6, #0
	add	r2, r2, #0x10
	add	r1, r1, #0x2
	ldrb	r0, [r6, #0x10]
	cmp	r0, #0
	beq	.L4	@cond_branch
.L5:
	ldrb	r0, [r2]
	strb	r0, [r1]
	add	r2, r2, #0x1
	add	r1, r1, #0x1
	ldrb	r0, [r2]
	cmp	r0, #0
	bne	.L5	@cond_branch
.L4:
	mov	r0, #0x81
	strb	r0, [r1]
	add	r1, r1, #0x1
	mov	r0, #0x76
	strb	r0, [r1]
	mov	r0, #0x0
	strb	r0, [r1, #0x1]
	ldr	r5, .L12
	mov	r2, #0xa2
	lsl	r2, r2, #0x3
	ldr	r4, [r5]
	ldr	r0, .L12+0x34
	add	r1, r7, #0
	mov	r3, sp
	bl	_call_via_r4
	ldr	r2, .L12+0x3c
	ldr	r3, .L12+0x40
	ldr	r4, [r5]
	mov	r0, #0xa4
	lsl	r0, r0, #0x2
	ldr	r1, .L12+0x20
	bl	_call_via_r4
	lsl	r0, r0, #0x18
	lsr	r7, r0, #0x18
	lsl	r1, r7, #0x8
	ldr	r2, [r5]
	ldr	r0, .L12+0x28
	bl	_call_via_r2
	ldr	r0, .L12+0x2c
	mov	sl, r0
	ldr	r3, [r5]
	add	r1, r7, #0
	mov	r2, #0x0
	bl	_call_via_r3
	ldr	r0, .L12+0x30
	mov	r8, r0
	ldr	r2, [r5]
	add	r1, r7, #0
	bl	_call_via_r2
	mov	r6, #0xa6
	lsl	r6, r6, #0x2
	mov	r0, #0x80
	lsl	r0, r0, #0x1
	mov	r9, r0
	ldr	r3, [r5]
	add	r0, r6, #0
	add	r1, r7, #0
	mov	r2, r9
	bl	_call_via_r3
	ldr	r3, .L12+0x44
	ldr	r4, [r5]
	mov	r0, #0xa4
	lsl	r0, r0, #0x2
	ldr	r1, .L12+0x20
	mov	r2, #0x0
	bl	_call_via_r4
	add	r4, r0, #0
	lsl	r4, r4, #0x18
	lsr	r4, r4, #0x18
	lsl	r1, r4, #0x8
	mov	r0, #0x2
	orr	r1, r1, r0
	ldr	r2, [r5]
	ldr	r0, .L12+0x28
	bl	_call_via_r2
	ldr	r3, [r5]
	mov	r0, sl
	add	r1, r4, #0
	mov	r2, #0x0
	bl	_call_via_r3
	ldr	r2, [r5]
	mov	r0, r8
	add	r1, r4, #0
	bl	_call_via_r2
	ldr	r3, [r5]
	add	r0, r6, #0
	add	r1, r4, #0
	mov	r2, r9
	bl	_call_via_r3
	ldr	r2, .L12+0x48
	ldr	r3, .L12+0x4c
	ldr	r6, [r5]
	ldr	r0, .L12+0x34
	add	r1, r4, #0
	bl	_call_via_r6
	ldr	r0, .L12+0x50
	ldr	r3, [r5]
	mov	r1, #0x10
	mov	r2, #0x23
	bl	_call_via_r3
	mov	r0, #0x80
	lsl	r0, r0, #0x2
	ldr	r2, [r5]
	mov	r1, #0x10
	bl	_call_via_r2
	mov	r4, #0x0
	ldr	r0, .L12+0x54
	strb	r4, [r0]
	add	r6, r0, #0
.L7:
	ldr	r2, [r5]
	mov	r0, #0xc0
	lsl	r0, r0, #0x2
	mov	r1, #0x1
	bl	_call_via_r2
	add	r0, r4, #0
	bl	sub_020008A4
	strb	r0, [r6]
	add	r0, r7, #0
	bl	sub_020009A0
	ldr	r1, [r5]
	ldr	r0, .L12+0x58
	bl	_call_via_r1
	lsl	r0, r0, #0x10
	lsr	r4, r0, #0x10
	ldrb	r0, [r6]
	cmp	r0, #0
	beq	.L7	@cond_branch
	mov	r0, #0x2
	add	sp, sp, #0x100
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
.L13:
	.align	2, 0
.L12:
	.word	gSomeFuncPtr
	.word	0x2ea
	.word	0x27e
	.word	gUnknown_02001070
	.word	gUnknown_02000D48
	.word	gUnknown_02000D8C
	.word	0x2c3
	.word	sub_020005C4
	.word	0x101
	.word	0x1e03
	.word	0x29a
	.word	0x291
	.word	0x292
	.word	0x299
	.word	gUnknown_02000AB4
	.word	0x105
	.word	0x1e10
	.word	0x1e02
	.word	0x402
	.word	gUnknown_02000AE0
	.word	0x21a
	.word	gUnknown_020010B4
	.word	0x301
.Lfe1:
	.size	 AgbMain,.Lfe1-AgbMain
